package View;


import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malik
 */
public class Admin_MenuAdmin extends javax.swing.JFrame {
    /**
     * Creates new form MenuAdmin
     */
    public Admin_MenuAdmin() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        A_tblReqPinjaman = new javax.swing.JTable();
        A_btnTerima = new javax.swing.JButton();
        A_btnTolak = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        A_btnInputSimpan = new javax.swing.JButton();
        A_btnInputBayar = new javax.swing.JButton();
        A_btnLihatSimpan = new javax.swing.JButton();
        A_btnLihatPinjam = new javax.swing.JButton();
        A_btnInputPenarikan = new javax.swing.JButton();
        A_btnLihatPenarikan = new javax.swing.JButton();
        A_btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REQUEST PINJAMAN USER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        A_tblReqPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Anggota", "Nama", "Tanggal Pinjam", "Keterangan", "Jumlah Pinjam"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(A_tblReqPinjaman);

        A_btnTerima.setText("Terima");
        A_btnTerima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnTerimaMouseClicked(evt);
            }
        });
        A_btnTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnTerimaActionPerformed(evt);
            }
        });

        A_btnTolak.setText("Tolak");
        A_btnTolak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnTolakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A_btnTerima)
                        .addGap(18, 18, 18)
                        .addComponent(A_btnTolak)
                        .addGap(0, 457, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A_btnTolak)
                    .addComponent(A_btnTerima))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "MENU ADMIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        A_btnInputSimpan.setText("Input Simpanan");
        A_btnInputSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnInputSimpanMouseClicked(evt);
            }
        });

        A_btnInputBayar.setText("Input Pelunasan");
        A_btnInputBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnInputBayarActionPerformed(evt);
            }
        });

        A_btnLihatSimpan.setText("Lihat Simpanan");
        A_btnLihatSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnLihatSimpanActionPerformed(evt);
            }
        });

        A_btnLihatPinjam.setText("Lihat Pinjaman");
        A_btnLihatPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnLihatPinjamMouseClicked(evt);
            }
        });
        A_btnLihatPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnLihatPinjamActionPerformed(evt);
            }
        });

        A_btnInputPenarikan.setText("Input Penarikan");
        A_btnInputPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnInputPenarikanActionPerformed(evt);
            }
        });

        A_btnLihatPenarikan.setText("Lihat Penarikan");
        A_btnLihatPenarikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnLihatPenarikanMouseClicked(evt);
            }
        });
        A_btnLihatPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnLihatPenarikanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A_btnInputSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_btnLihatSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A_btnLihatPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_btnInputBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(A_btnLihatPenarikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_btnInputPenarikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A_btnInputSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_btnInputBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_btnInputPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A_btnLihatSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_btnLihatPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A_btnLihatPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        A_btnLogout.setText("LOGOUT");
        A_btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnLogoutMouseClicked(evt);
            }
        });
        A_btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/KOSERMENUDADMIN.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(A_btnLogout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(A_btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_btnTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnTerimaActionPerformed
    }//GEN-LAST:event_A_btnTerimaActionPerformed

    private void A_btnTerimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnTerimaMouseClicked

    }//GEN-LAST:event_A_btnTerimaMouseClicked

    private void A_btnLihatPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnLihatPinjamMouseClicked

    }//GEN-LAST:event_A_btnLihatPinjamMouseClicked

    private void A_btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnLogoutMouseClicked

    }//GEN-LAST:event_A_btnLogoutMouseClicked

    private void A_btnLihatSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnLihatSimpanActionPerformed
    
    }//GEN-LAST:event_A_btnLihatSimpanActionPerformed

    private void A_btnInputSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnInputSimpanMouseClicked
    
    }//GEN-LAST:event_A_btnInputSimpanMouseClicked

    private void A_btnLihatPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnLihatPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btnLihatPinjamActionPerformed

    private void A_btnTolakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnTolakMouseClicked
    
    }//GEN-LAST:event_A_btnTolakMouseClicked

    private void A_btnInputBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnInputBayarActionPerformed
    
    }//GEN-LAST:event_A_btnInputBayarActionPerformed

    private void A_btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btnLogoutActionPerformed

    private void A_btnInputPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnInputPenarikanActionPerformed
    
    }//GEN-LAST:event_A_btnInputPenarikanActionPerformed

    private void A_btnLihatPenarikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnLihatPenarikanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_A_btnLihatPenarikanMouseClicked

    private void A_btnLihatPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnLihatPenarikanActionPerformed
    
    }//GEN-LAST:event_A_btnLihatPenarikanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_btnInputBayar;
    private javax.swing.JButton A_btnInputPenarikan;
    private javax.swing.JButton A_btnInputSimpan;
    private javax.swing.JButton A_btnLihatPenarikan;
    private javax.swing.JButton A_btnLihatPinjam;
    private javax.swing.JButton A_btnLihatSimpan;
    private javax.swing.JButton A_btnLogout;
    private javax.swing.JButton A_btnTerima;
    private javax.swing.JButton A_btnTolak;
    private javax.swing.JTable A_tblReqPinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
