package View;


import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malik
 */
public class Admin_MenuAdmin extends javax.swing.JFrame {
    /**
     * Creates new form MenuAdmin
     */
    public Admin_MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLihatPinjam = new javax.swing.JButton();
        btnLihatPenarikan = new javax.swing.JButton();
        btnLihatSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnInputSimpan = new javax.swing.JButton();
        btnInputPenarikan = new javax.swing.JButton();
        btnInputBayar = new javax.swing.JButton();
        btnTerimaPinjaman = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Admin");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(245, 238, 248));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(235, 222, 240));

        jPanel2.setBackground(new java.awt.Color(245, 238, 248));

        btnLihatPinjam.setBackground(new java.awt.Color(84, 160, 255));
        btnLihatPinjam.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnLihatPinjam.setText("LIHAT PINJAMAN");
        btnLihatPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatPinjamMouseClicked(evt);
            }
        });
        btnLihatPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPinjamActionPerformed(evt);
            }
        });

        btnLihatPenarikan.setBackground(new java.awt.Color(84, 160, 255));
        btnLihatPenarikan.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnLihatPenarikan.setText("LIHAT PENARIKAN");
        btnLihatPenarikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatPenarikanMouseClicked(evt);
            }
        });
        btnLihatPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPenarikanActionPerformed(evt);
            }
        });

        btnLihatSimpan.setBackground(new java.awt.Color(84, 160, 255));
        btnLihatSimpan.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnLihatSimpan.setText("LIHAT SIMPANAN");
        btnLihatSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLihatPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLihatPenarikan, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addComponent(btnLihatSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnLihatSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLihatPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLihatPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(245, 238, 248));

        btnInputSimpan.setBackground(new java.awt.Color(84, 160, 255));
        btnInputSimpan.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnInputSimpan.setText("INPUT SIMPANAN");
        btnInputSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInputSimpanMouseClicked(evt);
            }
        });
        btnInputSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputSimpanActionPerformed(evt);
            }
        });

        btnInputPenarikan.setBackground(new java.awt.Color(84, 160, 255));
        btnInputPenarikan.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnInputPenarikan.setText("INPUT PENARIKAN");
        btnInputPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPenarikanActionPerformed(evt);
            }
        });

        btnInputBayar.setBackground(new java.awt.Color(84, 160, 255));
        btnInputBayar.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnInputBayar.setText("INPUT PELUNASAN");
        btnInputBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputBayarActionPerformed(evt);
            }
        });

        btnTerimaPinjaman.setBackground(new java.awt.Color(22, 160, 133));
        btnTerimaPinjaman.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        btnTerimaPinjaman.setText("TERIMA PINJAMAN");
        btnTerimaPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaPinjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTerimaPinjaman)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnInputBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                        .addComponent(btnInputPenarikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInputSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTerimaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnInputSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInputPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInputBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        btnLogout.setBackground(new java.awt.Color(192, 57, 43));
        btnLogout.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setToolTipText("");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/menuadmin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatPinjamMouseClicked

    }//GEN-LAST:event_btnLihatPinjamMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLihatSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatSimpanActionPerformed
    
    }//GEN-LAST:event_btnLihatSimpanActionPerformed

    private void btnInputSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputSimpanMouseClicked
    
    }//GEN-LAST:event_btnInputSimpanMouseClicked

    private void btnLihatPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatPinjamActionPerformed

    private void btnInputBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputBayarActionPerformed
    
    }//GEN-LAST:event_btnInputBayarActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInputPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPenarikanActionPerformed
    
    }//GEN-LAST:event_btnInputPenarikanActionPerformed

    private void btnLihatPenarikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatPenarikanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLihatPenarikanMouseClicked

    private void btnLihatPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPenarikanActionPerformed
    
    }//GEN-LAST:event_btnLihatPenarikanActionPerformed

    private void btnTerimaPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaPinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerimaPinjamanActionPerformed

    private void btnInputSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputSimpanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputBayar;
    private javax.swing.JButton btnInputPenarikan;
    private javax.swing.JButton btnInputSimpan;
    private javax.swing.JButton btnLihatPenarikan;
    private javax.swing.JButton btnLihatPinjam;
    private javax.swing.JButton btnLihatSimpan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTerimaPinjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnInputBayar() {
        return btnInputBayar;
    }

    public JButton getBtnInputPenarikan() {
        return btnInputPenarikan;
    }

    public JButton getBtnInputSimpan() {
        return btnInputSimpan;
    }

    public JButton getBtnLihatPenarikan() {
        return btnLihatPenarikan;
    }

    public JButton getBtnLihatPinjam() {
        return btnLihatPinjam;
    }

    public JButton getBtnLihatSimpan() {
        return btnLihatSimpan;
    }

    public JButton getBtnTerimaPinjaman() {
        return btnTerimaPinjaman;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public void addActionListener(ActionListener x){
        btnTerimaPinjaman.addActionListener(x);
        btnInputSimpan.addActionListener(x);
        btnInputPenarikan.addActionListener(x);
        btnInputBayar.addActionListener(x);
        btnLihatSimpan.addActionListener(x);
        btnLihatPenarikan.addActionListener(x);
        btnLihatPinjam.addActionListener(x);
        btnLogout.addActionListener(x);
    }
}
