package View;




import Controller.ControllerReqPinjaman;
import Model.Pinjaman;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import static java.lang.Math.ceil;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malik
 */
public class User_ReqPinjam extends javax.swing.JFrame {
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    
    public User_ReqPinjam() {
        initComponents();
        this.setLocationRelativeTo(null);
        U_txDatePinjam.setText(format.format(new Date())+"");
    }

    public JTextField getU_txDatePinjam() {
        return U_txDatePinjam;
    }

    public JTextField getU_txKetPinjam() {
        return U_txKetPinjam;
    }

    public JButton getU_ReqbtnCancel() {
        return U_ReqbtnCancel;
    }

    public JButton getU_ReqbtnOK() {
        return U_ReqbtnOK;
    }

    public JButton getU_ReqbtnReset() {
        return U_ReqbtnReset;
    }

    public JTextField getU_txJumPinjam() {
        return U_txJumPinjam;
    }
    
    public void addListener(ActionListener e){
        U_ReqbtnCancel.addActionListener(e);
        U_ReqbtnOK.addActionListener(e);
        U_ReqbtnReset.addActionListener(e);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        U_txDatePinjam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        U_txKetPinjam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        U_txJumPinjam = new javax.swing.JTextField();
        U_ReqbtnOK = new javax.swing.JButton();
        U_ReqbtnReset = new javax.swing.JButton();
        U_ReqbtnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setEnabled(false);

        U_txDatePinjam.setEditable(false);
        U_txDatePinjam.setText("dd/mm/yy");
        U_txDatePinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_txDatePinjamActionPerformed(evt);
            }
        });

        jLabel1.setText("Keterangan Pinjam");

        jLabel2.setText("Tanggal Pinjam");

        U_txKetPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_txKetPinjamActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah Pinjam");

        U_txJumPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_txJumPinjamActionPerformed(evt);
            }
        });

        U_ReqbtnOK.setBackground(new java.awt.Color(26, 188, 156));
        U_ReqbtnOK.setText("OK");
        U_ReqbtnOK.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        U_ReqbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_ReqbtnOKActionPerformed(evt);
            }
        });

        U_ReqbtnReset.setBackground(new java.awt.Color(244, 208, 63));
        U_ReqbtnReset.setText("RESET");
        U_ReqbtnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        U_ReqbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_ReqbtnResetActionPerformed(evt);
            }
        });

        U_ReqbtnCancel.setBackground(new java.awt.Color(192, 57, 43));
        U_ReqbtnCancel.setText("CANCEL");
        U_ReqbtnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        U_ReqbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_ReqbtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(U_ReqbtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(U_ReqbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(U_ReqbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(U_txDatePinjam)
                    .addComponent(U_txKetPinjam)
                    .addComponent(U_txJumPinjam))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(U_txDatePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(U_txKetPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(U_txJumPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(U_ReqbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(U_ReqbtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(U_ReqbtnOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/KoseruPinjam.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void U_txKetPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_txKetPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_txKetPinjamActionPerformed

    private void U_txJumPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_txJumPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_txJumPinjamActionPerformed

    private void U_txDatePinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_txDatePinjamActionPerformed
        
    }//GEN-LAST:event_U_txDatePinjamActionPerformed

    private void U_ReqbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_ReqbtnOKActionPerformed

    }//GEN-LAST:event_U_ReqbtnOKActionPerformed

    private void U_ReqbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_ReqbtnResetActionPerformed

    }//GEN-LAST:event_U_ReqbtnResetActionPerformed

    private void U_ReqbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_ReqbtnCancelActionPerformed

    }//GEN-LAST:event_U_ReqbtnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton U_ReqbtnCancel;
    private javax.swing.JButton U_ReqbtnOK;
    private javax.swing.JButton U_ReqbtnReset;
    private javax.swing.JTextField U_txDatePinjam;
    private javax.swing.JTextField U_txJumPinjam;
    private javax.swing.JTextField U_txKetPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
