package View;




import Controller.ControllerUserMenu;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class User_MenuUser extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuUser
     */
    public User_MenuUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public void addListenerMUser(ActionListener e){
        U_btnCekSaldo.addActionListener(e);
        U_btnEdit.addActionListener(e);
        U_btnLogout.addActionListener(e);
        U_btnReqPinjam.addActionListener(e);
    }

    public JButton getU_btnCekSaldo() {
        return U_btnCekSaldo;
    }

    public JButton getU_btnEdit() {
        return U_btnEdit;
    }

    public JButton getU_btnLogout() {
        return U_btnLogout;
    }

    public JButton getU_btnReqPinjam() {
        return U_btnReqPinjam;
    }

    public JTextField getU_txEmail() {
        return U_txEmail;
    }

    public JTextField getU_txKd_Anggota() {
        return U_txKd_Anggota;
    }

    public JTextField getU_txNama() {
        return U_txNama;
    }

    public JTextField getU_txAlamat() {
        return U_txAlamat;
    }

    public JTextField getU_txJk() {
        return U_txJk;
    }

    public JTextField getU_txProfesi() {
        return U_txProfesi;
    }

    public JTextField getU_txTTL() {
        return U_txTTL;
    }

    public JTable getU_tbPelunasan() {
        return U_tbPelunasan;
    }

    public JTable getU_tbPenarikan() {
        return U_tbPenarikan;
    }

    public JTable getU_tbSimpan() {
        return U_tbSimpan;
    }

    public JTable getU_tblPinjam() {
        return U_tblPinjam;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        U_txNama = new javax.swing.JTextField();
        U_txKd_Anggota = new javax.swing.JTextField();
        U_txTTL = new javax.swing.JTextField();
        U_txEmail = new javax.swing.JTextField();
        U_txProfesi = new javax.swing.JTextField();
        U_btnEdit = new javax.swing.JButton();
        U_btnLogout = new javax.swing.JButton();
        U_btnReqPinjam = new javax.swing.JButton();
        U_btnCekSaldo = new javax.swing.JButton();
        U_txAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        U_txJk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTerimaPinjaman = new javax.swing.JButton();
        btnTerimaPinjaman2 = new javax.swing.JButton();
        btnTerimaPinjaman3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATA DIRI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Nama");

        jLabel2.setText("Kode Anggota");

        jLabel3.setText("Profesi");

        jLabel4.setText("TTL");

        jLabel5.setText("Email");

        U_txNama.setEditable(false);
        U_txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_txNamaActionPerformed(evt);
            }
        });

        U_txKd_Anggota.setEditable(false);

        U_txTTL.setEditable(false);

        U_txEmail.setEditable(false);

        U_txProfesi.setEditable(false);

        U_btnEdit.setBackground(new java.awt.Color(253, 203, 110));
        U_btnEdit.setText("EDIT PROFILE");
        U_btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_btnEditActionPerformed(evt);
            }
        });

        U_btnLogout.setBackground(new java.awt.Color(192, 57, 43));
        U_btnLogout.setText("LOGOUT");
        U_btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U_btnLogoutMouseClicked(evt);
            }
        });

        U_btnReqPinjam.setBackground(new java.awt.Color(26, 188, 156));
        U_btnReqPinjam.setText("REQ PINJAMAN");
        U_btnReqPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_btnReqPinjamActionPerformed(evt);
            }
        });

        U_btnCekSaldo.setBackground(new java.awt.Color(26, 188, 156));
        U_btnCekSaldo.setText("CEK SALDO");
        U_btnCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_btnCekSaldoActionPerformed(evt);
            }
        });

        U_txAlamat.setEditable(false);

        jLabel7.setText("Alamat");

        U_txJk.setEditable(false);

        jLabel8.setText("Jenis Kelamin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(U_txNama)
                            .addComponent(U_txKd_Anggota)
                            .addComponent(U_txTTL)
                            .addComponent(U_txEmail)
                            .addComponent(U_txProfesi, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(U_txAlamat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(U_txJk, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(U_btnCekSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(U_btnEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(U_btnReqPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(U_btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(U_txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(U_txKd_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(U_txTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(U_txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(U_txProfesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(U_txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(U_txJk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(U_btnReqPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U_btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(U_btnCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(U_btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/KoseruUsrMenu.png"))); // NOI18N

        btnTerimaPinjaman.setBackground(new java.awt.Color(84, 160, 255));
        btnTerimaPinjaman.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnTerimaPinjaman.setText("LIHAT PINJAMAN");
        btnTerimaPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaPinjamanActionPerformed(evt);
            }
        });

        btnTerimaPinjaman2.setBackground(new java.awt.Color(84, 160, 255));
        btnTerimaPinjaman2.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnTerimaPinjaman2.setText("LIHAT PENARIKAN");
        btnTerimaPinjaman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaPinjaman2ActionPerformed(evt);
            }
        });

        btnTerimaPinjaman3.setBackground(new java.awt.Color(84, 160, 255));
        btnTerimaPinjaman3.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        btnTerimaPinjaman3.setText("LIHAT SIMPANAN");
        btnTerimaPinjaman3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaPinjaman3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("ini adalah menu user");

        jLabel10.setFont(new java.awt.Font("Schadow BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Silahkan tekan tombol untuk menuju menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTerimaPinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTerimaPinjaman2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTerimaPinjaman3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(78, 78, 78)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTerimaPinjaman2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTerimaPinjaman3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTerimaPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void U_txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_txNamaActionPerformed

    private void U_btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_btnEditActionPerformed
    
    }//GEN-LAST:event_U_btnEditActionPerformed

    private void U_btnReqPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_btnReqPinjamActionPerformed
    
    }//GEN-LAST:event_U_btnReqPinjamActionPerformed

    private void U_btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U_btnLogoutMouseClicked
    
    }//GEN-LAST:event_U_btnLogoutMouseClicked

    private void U_btnCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_btnCekSaldoActionPerformed

    }//GEN-LAST:event_U_btnCekSaldoActionPerformed

    private void btnTerimaPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaPinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerimaPinjamanActionPerformed

    private void btnTerimaPinjaman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaPinjaman2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerimaPinjaman2ActionPerformed

    private void btnTerimaPinjaman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaPinjaman3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerimaPinjaman3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton U_btnCekSaldo;
    private javax.swing.JButton U_btnEdit;
    private javax.swing.JButton U_btnLogout;
    private javax.swing.JButton U_btnReqPinjam;
    private javax.swing.JTextField U_txAlamat;
    private javax.swing.JTextField U_txEmail;
    private javax.swing.JTextField U_txJk;
    private javax.swing.JTextField U_txKd_Anggota;
    private javax.swing.JTextField U_txNama;
    private javax.swing.JTextField U_txProfesi;
    private javax.swing.JTextField U_txTTL;
    private javax.swing.JButton btnTerimaPinjaman;
    private javax.swing.JButton btnTerimaPinjaman2;
    private javax.swing.JButton btnTerimaPinjaman3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
