


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hsqldb.error.ErrorCode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malik
 */
public class Admin_InputPenarikan extends javax.swing.JFrame {
    private DatabasePenarikan dp = new DatabasePenarikan();
    SimpleDateFormat format = new SimpleDateFormat("dd MMMMM yyyy");
    /**
     * Creates new form Admin_InputPenarikan
     */
    public Admin_InputPenarikan() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A_tglTarik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        A_txJumTarik = new javax.swing.JTextField();
        A_btnOK = new javax.swing.JButton();
        A_btnReset = new javax.swing.JButton();
        A_btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        A_txkdAnggota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        A_txNama = new javax.swing.JTextField();
        A_btnCari = new javax.swing.JButton();
        A_txSaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Penarikan");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT PENARIKAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setFocusable(false);

        A_tglTarik.setEditable(false);
        A_tglTarik.setText("dd/mm/yyyy");

        jLabel2.setText("Tanggal Simpan");

        jLabel5.setText("Jumlah Penarikan");

        A_txJumTarik.setText("0");
        A_txJumTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_txJumTarikActionPerformed(evt);
            }
        });

        A_btnOK.setText("OK");
        A_btnOK.setEnabled(false);
        A_btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnOKActionPerformed(evt);
            }
        });

        A_btnReset.setText("Reset");
        A_btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnResetActionPerformed(evt);
            }
        });

        A_btnCancel.setText("Cancel");
        A_btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_btnCancelMouseClicked(evt);
            }
        });

        jLabel6.setText("Kode Anggota");

        A_txkdAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_txkdAnggotaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        A_txNama.setEditable(false);
        A_txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_txNamaActionPerformed(evt);
            }
        });

        A_btnCari.setText("Cari");
        A_btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btnCariActionPerformed(evt);
            }
        });

        A_txSaldo.setEditable(false);
        A_txSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_txSaldoActionPerformed(evt);
            }
        });

        jLabel3.setText("Saldo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(A_btnOK)
                        .addGap(18, 18, 18)
                        .addComponent(A_btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(A_btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A_txSaldo)
                            .addComponent(A_txNama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(A_txkdAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addGap(15, 15, 15)
                                .addComponent(A_btnCari))
                            .addComponent(A_tglTarik))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(A_txJumTarik)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(A_tglTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(A_txkdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(A_txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(A_txSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(A_txJumTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A_btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_btnReset)
                    .addComponent(A_btnCancel))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Input Penarikan.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_txJumTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_txJumTarikActionPerformed
        
    }//GEN-LAST:event_A_txJumTarikActionPerformed

    private void A_txkdAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_txkdAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_txkdAnggotaActionPerformed

    private void A_btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnOKActionPerformed
    }//GEN-LAST:event_A_btnOKActionPerformed

    private void A_btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_btnCancelMouseClicked
        A_btnOK.setEnabled(false);
        A_txkdAnggota.setEditable(true);
        A_txkdAnggota.setText("");
        A_txNama.setText("");
        A_txJumTarik.setText("");
        A_txSaldo.setText("");
        this.dispose();
    }//GEN-LAST:event_A_btnCancelMouseClicked

    private void A_txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_txNamaActionPerformed

    private void A_btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnCariActionPerformed
    }//GEN-LAST:event_A_btnCariActionPerformed

    private void A_btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_btnResetActionPerformed
        A_txkdAnggota.setEditable(true);
        A_btnOK.setEnabled(false);
        A_txkdAnggota.setText("");
        A_txNama.setText("");
        A_txJumTarik.setText("");
        A_txSaldo.setText("");
    }//GEN-LAST:event_A_btnResetActionPerformed

    private void A_txSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_txSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_txSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_btnCancel;
    private javax.swing.JButton A_btnCari;
    private javax.swing.JButton A_btnOK;
    private javax.swing.JButton A_btnReset;
    private javax.swing.JTextField A_tglTarik;
    private javax.swing.JTextField A_txJumTarik;
    private javax.swing.JTextField A_txNama;
    private javax.swing.JTextField A_txSaldo;
    private javax.swing.JTextField A_txkdAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
